### ISSUE TITLE
Scanner Service Exception

### ISSUE THREAD

**Issue by teabarley** [johypark97/VArchiveMacro#1]
분석 시도 시 다음의 오류가 발생합니다. 

java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(Unknown Source)
	at java.base/java.util.concurrent.Executors.newFixedThreadPool(Unknown Source)
	at com.github.johypark97.varchivemacro.macro.fxgui.model.service.task.AnalysisTask.callTask(AnalysisTask.java:204)
	at com.github.johypark97.varchivemacro.macro.fxgui.model.service.task.AnalysisTask.callTask(AnalysisTask.java:45)
	at com.github.johypark97.varchivemacro.macro.fxgui.model.service.task.InterruptibleTask.call(InterruptibleTask.java:16)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by johypark97** [comment]
분석 작업 스레드 최적화 코드 병합 도중에 실수가 있었나보네요.

버그 제보 감사합니다.
