### ISSUE TITLE
업로드 중 IOException: GOAWAY received

### ISSUE THREAD

**Issue by teabarley** [johypark97/VArchiveMacro#3]
업로드 중 발생한 오류입니다. 이 오류가 발생하기 전까지 진행된 것들은 무사히 업로드가 완료됐고, 남은 것들도 업로드를 다시 진행하니 문제없이 완료됐지만, 추후 문제가 발생할 수도 있어 미리 제보합니다.

정확히는 2.4.0이 이미 설치된 폴더에 2.4.1을 그대로 붙여넣은 상황입니다.
번거롭게 해드려 죄송합니다. 연말 잘 보내세요.

java.io.IOException: /(컴퓨터 IP): GOAWAY received
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at com.github.johypark97.varchivemacro.lib.scanner.api.impl.RecordUploaderImpl.upload(RecordUploaderImpl.java:59)
	at com.github.johypark97.varchivemacro.macro.fxgui.model.service.task.UploadTask.callTask(UploadTask.java:113)
	at com.github.johypark97.varchivemacro.macro.fxgui.model.service.task.UploadTask.callTask(UploadTask.java:24)
	at com.github.johypark97.varchivemacro.macro.fxgui.model.service.task.InterruptibleTask.call(InterruptibleTask.java:16)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.io.IOException: /(컴퓨터 IP): GOAWAY received
	at java.net.http/jdk.internal.net.http.Http2Connection.handleGoAway(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection.handleConnectionFrame(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection.processFrame(Unknown Source)
	at java.net.http/jdk.internal.net.http.frame.FramesDecoder.decode(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection.asyncReceive(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by johypark97** [comment]
제보해주신 업로드 도중 발생한 오류는 v-archive 서버가 업로드 연결을 끊으며 발생하는 오류입니다.

> java.io.IOException: /(컴퓨터 IP): GOAWAY received

여기서 `GOAWAY`는 서버가 클라이언트에 보내는 HTTP2 연결 종료 프레임입니다.

해당 오류는 컬렉션 스캔 기능을 도입하기 시작한 _v1.1.0-alpha1_ 버전부터 지금까지 정말 드물게 제보된 문제로, 모두 한 번에 수백 건 이상의 많은 기록을 업로드할 때 발생하였습니다. 아마 단시간에 다량의 요청이 보내어지거나 많은 기록을 업로드함에 따라 연결이 비정상적으로 길어져 서버에서 연결을 끊으며 오류가 발생하는 것으로 보여집니다.

이렇게 발생한 오류는 일시적인 것이라 잠시 후 다시 업로드를 시도하면 정상 업로드가 가능하여 사용상 큰 문제는 없습니다.

대신에 에러 메시지가 알아보기 힘든 면이 있는데, 이와 관련해서 이 오류 뿐만 아니라 프로그램 전체적으로 오류 메시지를 다듬을 계획이 있습니다. 다른 계획들에 비해서 우선순위가 낮아 언제가 될지는 모르겠지만 이때 오류 메시지가 아닌 안내 메시지로 형태를 변경하는 쪽이 나아보이네요.

제보 감사합니다. 남은 연말 마무리 잘 하시고 내년에도 복 많이 받으시길 바랍니다.

혹시 더 궁금하신 점 있으신가요?

**Comment by teabarley** [comment]
아하 단순한 일시적 오류였다고 하니 다행이네요. 말씀주신 것처럼 이러한 류의 '잠시 후 다시 시도하면 해결되는 오류들'은 에러 메시지를 그대로 띄우지 말고 '다시 한번 시도해 주세요' 등의 안내 메시지로 바꾸면 사용자 입장에서는 불안하지 않고 잘 사용할 수 있을 것 같습니다. 선생님도 새해 복 많이 받으세요.
